/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_genomedata_free: (a: number, b: number) => void;
export const genomedata_new: () => number;
export const genomedata_load_json: (a: number, b: number, c: number) => [number, number];
export const genomedata_load_binary: (a: number, b: number, c: number) => [number, number];
export const genomedata_get_ref_length: (a: number) => number;
export const genomedata_get_ref_name: (a: number) => [number, number];
export const genomedata_get_sample_ids: (a: number) => [number, number];
export const genomedata_get_sample_label: (a: number, b: number, c: number) => [number, number];
export const genomedata_get_pipeline_ids: (a: number) => [number, number];
export const genomedata_get_pipeline_label: (a: number, b: number, c: number) => [number, number];
export const genomedata_get_pipeline_command: (a: number, b: number, c: number) => [number, number];
export const genomedata_get_ground_truth_pipeline: (a: number) => [number, number];
export const genomedata_is_ground_truth: (a: number, b: number, c: number) => number;
export const genomedata_is_from_bam_pileup: (a: number, b: number, c: number) => number;
export const genomedata_get_vcf_pipelines: (a: number) => [number, number];
export const genomedata_get_generated_at: (a: number) => [number, number];
export const genomedata_get_warnings: (a: number) => [number, number];
export const genomedata_get_snps_in_gaps: (a: number) => [number, number];
export const genomedata_get_mnp_stats: (a: number) => [number, number];
export const genomedata_get_description: (a: number) => [number, number];
export const genomedata_get_pipeline_distance_matrices: (a: number) => [number, number];
export const genomedata_get_file_paths: (a: number) => [number, number];
export const genomedata_get_snp: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const genomedata_get_kpis: (a: number) => [number, number];
export const genomedata_get_global_stats: (a: number) => [number, number];
export const genomedata_get_global_stats_for_pipeline: (a: number, b: number, c: number) => [number, number];
export const genomedata_get_pairwise_usable_stats: (a: number) => [number, number];
export const genomedata_get_pairwise_usable_stats_for_pipeline: (a: number, b: number, c: number) => [number, number];
export const genomedata_get_reviewer_pairwise_stats: (a: number) => [number, number];
export const genomedata_get_gt_disc_vs_pipelines: (a: number) => [number, number];
export const genomedata_get_per_sample_stats: (a: number) => [number, number];
export const genomedata_get_pipeline_concordance: (a: number) => [number, number];
export const genomedata_get_per_sample_intersection_with_gt: (a: number) => [number, number];
export const genomedata_get_consensus_stats: (a: number) => [number, number];
export const genomedata_get_filtered_positions_v2: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const genomedata_render_filtered: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const genomedata_get_coverage_stats: (a: number) => [number, number];
export const genomedata_calculate_distance_matrix_filtered: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const init: () => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
